In [2]:
import pandas as pd
import numpy as np

path = "../IAA League Data/MATCHUP_DATA_2021.xlsx"
df = pd.read_excel(path)
df

,Week,MatchupId,Home/Away,Team,Player,Slot,Points,Eligible Slots
0,1,1,Home,Team Golaski,Dalvin Cook,RB,20.40,"RB, RB/WR, RB/WR/TE, OP, BE, IR"
1,1,1,Home,Team Golaski,Allen Robinson II,WR,9.50,"RB/WR, WR, WR/TE, RB/WR/TE, OP, BE, IR"
2,1,1,Home,Team Golaski,Chris Carson,RB,12.70,"RB, RB/WR, RB/WR/TE, OP, BE, IR"
3,1,1,Home,Team Golaski,T.J. Hockenson,TE,25.70,"WR/TE, TE, RB/WR/TE, OP, BE, IR"
4,1,1,Home,Team Golaski,Justin Herbert,QB,13.38,"QB, OP, BE, IR"
...,...,...,...,...,...,...,...,...
4587,17,136,Away,Team LaRusso,Browns D/ST,D/ST,0.00,"D/ST, BE, IR"
4588,17,136,Away,Team LaRusso,Jared Cook,BE,0.00,"WR/TE, TE, RB/WR/TE, OP, BE, IR"
4589,17,136,Away,Team LaRusso,Derek Carr,BE,0.00,"QB, OP, BE, IR"
4590,17,136,Away,Team LaRusso,Robbie Gould,K,0.00,"K, BE, IR"
4591,17,136,Away,Team LaRusso,Hunter Renfrow,BE,0.00,"RB/WR, WR, WR/TE, RB/WR/TE, OP, BE, IR"

In [18]:
teams = df["Team"].unique()
slots = ["QB", "RB", "RB", "WR", "WR", "TE", "RB/WR/TE", "D/ST", "K"]

for week in range(1, 18):
    week_df = df[df["Week"] == week]
    for team in teams:
        team_df = week_df[week_df["Team"] == team]
        team_df = team_df.sort_values("Points", ascending = False)
        first = True
        for slot in slots:
            top_player = team_df[team_df["Eligible Slots"].str.split(", ").contains(slot)].nlargest(1,'Points')
            if first:
                best_df = top_player
                first = False
            else:
                best_df.append(top_player)
            i = top_player.index
            team_df = team_df.drop(i)
        print(best_df)

AttributeError: 'Series' object has no attribute 'contains'

,Week,MatchupId,Home/Away,Team,Player,Slot,Points,Eligible Slots
4520,17,134,Away,Team Hospital,Daniel Carlson,K,0.0,"K, BE, IR"